name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate and Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: |
          echo "🔐 Authenticating using service account key..."
          export GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json
          firebase login:ci --no-localhost || echo "Skipping token creation, using service account"
          firebase use women-safest-route --add || echo "Using existing project"
          firebase deploy --only hosting --project women-safest-route --debug
